DROP DATABASE IF EXISTS HackerRank;
CREATE DATABASE HackerRank;

USE HackerRank;

CREATE TABLE CITY(
	ID				INT,
	NAME			VARCHAR(30),
    COUNTRYCODE		VARCHAR(3),
    DISTRICT		VARCHAR(20),
	POPULATION		INT,
    CONSTRAINT pk_city_id PRIMARY KEY (ID)
);

CREATE TABLE COUNTRY(
	CODE				VARCHAR(3),
    NAME				VARCHAR(44),
    CONTINENT			VARCHAR(13),
    REGION				VARCHAR(25),
    SURFACEAREA			INT,
    INDEPYEAR			VARCHAR(5),
    POPULATION			INT,
    LIFEEXPECTANCY		VARCHAR(4),
    GNP					INT,
    GNPOLD				VARCHAR(9),
    LOCALNAME			VARCHAR(44),
    GOVERNMENTFORM		VARCHAR(44),
    HEADOFSTATE			VARCHAR(32),
    CAPITAL				VARCHAR(4),
    CODE2				VARCHAR(2)
);

CREATE TABLE STATION(
	ID			INT,
    CITY		VARCHAR(50),
	STATE		VARCHAR(2),
	LAT_N		DECIMAL(7, 4),
	LONG_W		DECIMAL(7, 4),
    CONSTRAINT pk_station_id PRIMARY KEY (ID)
);

CREATE TABLE STUDENTS(
	ID		INT,
    Name	VARCHAR(50),
	Marks	INT,
    CONSTRAINT pk_students_id PRIMARY KEY (ID)
);

CREATE TABLE Employee(
	employee_id		INT,
	name			VARCHAR(50),
	months			INT,
	salary			INT,
    CONSTRAINT pk_employee_id PRIMARY KEY (employee_id)
);

CREATE TABLE Employees(
	ID		INT,
	Name			VARCHAR(50),
	Salary			INT,
    CONSTRAINT pk_employee_id PRIMARY KEY (ID)
);

CREATE TABLE TRIANGLES(
	A		INT,
    B		INT,
	C		INT
);

CREATE TABLE OCCUPATIONS(
	Name		VARCHAR(30),
    Occupation	VARCHAR(50)
);